### ISSUE TITLE
ActivityNet code requested

### ISSUE THREAD

**Issue by tzzcl** [PeisenZhao/Bottom-Up-TAL-with-MR#1]
Hi, I see your work on ECCV 2020. It is really an amazing paper.

But I found that your current repo only contains THUMOS implementations, will you provide ActivityNet features and implementations?

Thank you for your help!

**Comment by PeisenZhao** [comment]
You can download the features from https://pan.baidu.com/s/1KJxNE-_We-9AcBs0N6xTXA#list/path=%2F,
and the code on ActivityNet will provide later. Thanks!

**Comment by tzzcl** [comment]
Thank you for your kindness reply! I've downloaded the features and will try your repos! Thanks!
