### ISSUE TITLE
Confused about the paper result in ActivityNet1.3 dataset.

### ISSUE THREAD

**Issue by XiaoluDing** [PeisenZhao/Bottom-Up-TAL-with-MR#3]
After I read your creative paper and [homepage](https://peisenzhao.github.io/), I have a lot of respect for your persistent exploration in the field of TAL. However, while reading your ECCV2020 paper, I have a lot of doubts about the comparison of the paper results with SOTA, especially the comparison with BSN results on ActivityNet1.3 dataset. In Table-5 of your paper, the BSN corresponds to a mAp of 29.17, while the mAP for the Location task of the [BSN](https://arxiv.org/pdf/1806.02964.pdf) in ActivityNet1.3 is 30.03..

Also, In the closed issue, someone raised the [same doubt](https://github.com/PeisenZhao/Bottom-Up-TAL-with-MR/issues/2) that why not compare with ICCV2019 BMN, we know that BMN-ACU(val) is 67.10 and mAP(val) is 33.85.

Looking forward to your reply.

**Comment by PeisenZhao** [comment]
Sorry for that the "29.17" is a typo in another Lin's work... thank you very much! We will fix it.
As for the result on ActivityNet1.3, the perofomance is not well, compared with BMN. We note that the regularization loss rules out a lot of action proposal while BMN use dense combination of starts and ends.  After improve the recall in futher sduty, we can also achieve 33 mAP on ActivityNet1.3.

I think the main contribution of this paper is the proposed regularization for learning better actionness (i.e., start, continue, end). I hope it can helps you when you applied it in your study. We also provide a pytorch implementation.

If you have any problem please let me know. You can email me with pszhao@sjtu.edu.cn

**Comment by PeisenZhao** [comment]
Hi Chenglu,


Sorry for that the "29.17" is a typo in another Lin's work... thank you very much! We will fix it.
As for the result on ActivityNet1.3, the perofomance is not well, compared with BMN. We note that the regularization loss rules out a lot of action proposal while BMN use dense combination of starts and ends.&nbsp; After improve the recall in futher sduty, we can also achieve 33 mAP on ActivityNet1.3.&nbsp;



I think the main contribution of this paper is the proposed regularization for learning better actionness (i.e., start, continue, end). I hope it can helps you when you applied it in your study. We also provide a pytorch implementation.


If you have any problem please let me know. You can email me with pszhao@sjtu.edu.cn


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PeisenZhao/Bottom-Up-TAL-with-MR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 晚上8:14
收件人:&nbsp;"PeisenZhao/Bottom-Up-TAL-with-MR"<Bottom-Up-TAL-with-MR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PeisenZhao/Bottom-Up-TAL-with-MR] Confused about the paper result in ActivityNet1.3 dataset. (#3)





 
After I read your creative paper and homepage, I have a lot of respect for your persistent exploration in the field of TAL. However, while reading your ECCV2020 paper, I have a lot of doubts about the comparison of the paper results with SOTA, especially the comparison with BSN results on ActivityNet1.3 dataset. In the closed issue, someone raised the same doubt that why not compare with ICCV2019 BMN, we know that BMN-ACU(val) is 67.10 and mAP(val) is 33.85.
 
Looking forward to your reply.

**Comment by XiaoluDing** [comment]
Thank you for your reply, The TAL is a very challenging task. Looking forward to more creative papers from you.
